on: [push, pull_request]

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  linux:
    name: Linux (CentOS 7)
    runs-on: ubuntu-latest
    container: centos:7

    steps:

    - name: Install
      run: yum install -y gcc gcc-c++ wget make python3

    - name: Install ninja-build
      run: |
        yum -y install https://download-ib01.fedoraproject.org/pub/epel/7/x86_64/Packages/n/ninja-build-1.10.2-3.el7.x86_64.rpm
        yum install -y ninja-build

    - name: Install recent git yay
      run: |
        yum -y install https://packages.endpointdev.com/rhel/7/os/x86_64/endpoint-repo.x86_64.rpm
        yum install -y git

    - name: Install AWS client
      run: |
        curl -O https://bootstrap.pypa.io/pip/3.6/get-pip.py
        python3 get-pip.py --user
        python3 -m pip install awscli --upgrade --user

    - name: Install CMake
      run: |
        wget https://github.com/Kitware/CMake/releases/download/v3.24.2/cmake-3.24.2-linux-x86_64.sh
        chmod +x cmake-3.24.2-linux-x86_64.sh
        mkdir -p /opt/cmake
        ./cmake-3.24.2-linux-x86_64.sh --skip-license --prefix=/opt/cmake
        echo "/opt/cmake/bin" >> $GITHUB_PATH

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'recursive'

    - name: Update DuckDB submodule
      run: |
        git config --global --add safe.directory '*'
        make pull

    - name: Build
      run: make release
      env:
        GEN: ninja

    - name: Make tpch test database
      run: |
        ./build/release/duckdb < tpch-export.duckdb
        sqlite3 tpch.db < tpch-create.sqlite

    - name: Test
      run: ./build/release/test/unittest --test-dir . "[lite_scanner]"

    - uses: actions/upload-artifact@v2
      with:
        name: sqlite-scanner-linux
        path: |
          build/release/extension/sqlite_scanner/sqlite_scanner.duckdb_extension
          
          

  windows:
    name: Windows (64-bit)
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Build
      run: |
        make

    - name: Make tpch test database
      run: |
        ./build/release/Release/duckdb.exe < tpch-export.duckdb
        choco install sqlite -y
        sqlite3 tpch.db < tpch-create.sqlite

    - name: Test
      run: ./build/release/test/Release/unittest.exe --test-dir . "[lite_scanner]"

    - uses: actions/upload-artifact@v2
      with:
        name: sqlite-scanner-windows
        path: |
          build/release/extension/sqlite_scanner/sqlite_scanner.duckdb_extension
          