on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: CentOS 7
    runs-on: ubuntu-latest
    container: centos:7

    steps:


    - name: Install
      run: yum install -y gcc gcc-c++ cmake make

    - name: Install recent git yay
      run: |
        yum -y install https://packages.endpoint.com/rhel/7/os/x86_64/endpoint-repo-1.9-1.x86_64.rpm
        yum install -y git

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Update DuckDB submodule
      run:  git submodule update --remote --merge

    - name: Build
      run: make release

    - name: Test
      run: ./duckdb/build/release/test/unittest --test-dir . "[lite_scanner]"

    - uses: actions/upload-artifact@v2
      with:
        name: sqlite-scanner
        path: |
          build/release/sqlite_scanner.duckdb_extension
