on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: CentOS 7
    runs-on: ubuntu-latest
    container: centos:7

    steps:

    - name: Install
      run: yum install -y gcc gcc-c++ cmake make python3

    - name: Install recent git yay
      run: |
        yum -y install https://packages.endpointdev.com/rhel/7/os/x86_64/endpoint-repo.x86_64.rpm
        yum install -y git

    - name: Install AWS client
      run: |
        curl -O https://bootstrap.pypa.io/pip/3.6/get-pip.py
        python3 get-pip.py --user
        python3 -m pip install awscli --upgrade --user

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Update DuckDB submodule
      run: |
        git submodule init
        git submodule update --remote --merge

    - name: Build
      run: make release duckdb_release

    - name: Make tpch test database
      run: |
        ./duckdb/build/release/duckdb < tpch-export.duckdb
        sqlite3 tpch.db < tpch-create.sqlite

    - name: Test
      run: ./duckdb/build/release/test/unittest --test-dir . "[lite_scanner]"

    - uses: actions/upload-artifact@v2
      with:
        name: sqlite-scanner
        path: |
          build/release/sqlite_scanner.duckdb_extension